---
- name: Sync backup files to AWS S3
  community.aws.s3_sync:
    access_key: "{{ access_key }}"
    secret_key: "{{ secret_access_key }}"
    bucket: "{{ bucket_name }}"
    file_root: /backup/
    storage_class: STANDARD
  register: s3_sync_result
  ignore_errors: yes

- name: Updating backup failed
  ansible.builtin.replace:
    path: /var/monitoring/data.ini
    regexp: 'backupS3 = .*'
    replace: 'backupS3 = failed'
  when: s3_sync_result.failed

- name: Updating backup success
  ansible.builtin.replace:
    path: /var/monitoring/data.ini
    regexp: 'backupS3 = .*'
    replace: 'backupS3 = success'
  when: s3_sync_result.changed
